; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DENABLE_OTA=1
lib_deps = 
	https://github.com/sparkfun/SparkFun_BNO080_Arduino_Library.git
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
    adafruit/Adafruit BNO055@^1.6.4
    adafruit/Adafruit Unified Sensor

[env:esp32dev_calibration]
extends = env:esp32dev
build_src_filter = +<servo.cpp> +<../calibration/servo_calibration.cpp>

[env:esp32deb_OTA]
extends = env:esp32dev
upload_protocol = espota
upload_port = 172.20.10.7

upload_flags =
	--port=3232
	--auth=Flerds@1!
