; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Project .env loading script
[env:esp32dev]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DENABLE_OTA=1
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
lib_deps =
	adafruit/Adafruit BMP280 Library@^3.0.0
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
    adafruit/Adafruit BNO055@^1.6.4
    adafruit/Adafruit Unified Sensor

[env:esp32dev_calibration]
extends = env:esp32dev
build_src_filter = +<servo.cpp> +<../calibration/servo_calibration.cpp>

[env:esp32dev_verbose]
extends = env:esp32dev
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DENABLE_OTA=1
	-DVERBOSE_SERIAL=1

[env:esp32deb_OTA]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.4.1
extra_scripts =
	pre:scripts/ota_auth.py
